"""extend agent runs and add tool calls

Revision ID: acffb4359668
Revises: 50683374f9bd
Create Date: 2026-08-31 18:47:12.533484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acffb4359668'
down_revision: Union[str, Sequence[str], None] = '50683374f9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('deduplicated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'sequence', name='uq_tool_calls_run_sequence')
    )
    op.add_column('agent_runs', sa.Column('halt_reason', sa.String(), nullable=True))
    op.add_column('agent_runs', sa.Column('iterations', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('result', sa.Text(), nullable=True))
    op.add_column('agent_runs', sa.Column('error', sa.Text(), nullable=True))
    op.create_index('ix_agent_runs_task_id_started_at', 'agent_runs', ['task_id', 'started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.drop_constraint(op.f('agent_runs_task_id_fkey'), 'agent_runs', type_='foreignkey')
    op.create_foreign_key(
        'agent_runs_task_id_fkey',
        'agent_runs',
        'tasks',
        ['task_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agent_runs_task_id_fkey', 'agent_runs', type_='foreignkey')
    op.create_foreign_key(
        'agent_runs_task_id_fkey', 'agent_runs', 'tasks', ['task_id'], ['id']
    )
    op.drop_index(
        'ix_agent_runs_task_id_started_at',
        table_name='agent_runs',
        postgresql_ops={'started_at': 'DESC'},
    )
    op.drop_column('agent_runs', 'error')
    op.drop_column('agent_runs', 'result')
    op.drop_column('agent_runs', 'total_tokens')
    op.drop_column('agent_runs', 'completion_tokens')
    op.drop_column('agent_runs', 'prompt_tokens')
    op.drop_column('agent_runs', 'iterations')
    op.drop_column('agent_runs', 'halt_reason')
    op.drop_table('tool_calls')
    # ### end Alembic commands ###
